name: Golint
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'
      - run: go get -u golang.org/x/lint/golint
      - run: golint -set_exit_status ./...