name: Release
on:
  workflow_dispatch: {}
  release:
    types: [created]

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'
      - name: Build for Linux
        run: go build -o twproxy
        env:
          CGO_ENABLED: 0
          GOARCH: amd64
          GOOS: linux
      - name: Build for Windows
        run: go build -o twproxy.exe
        env:
          CGO_ENABLED: 0
          GOARCH: amd64
          GOOS: windows
      - name: Attach to release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'twproxy*'